# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4248531a5b2d35e0c841932f680625df3558c61339325aaf45d1443c9618ff8e27c9d8df9eaa5762d0d0dbd0fa75ac26de91d23c8666baac0be7ccda4cc74f61

test:
  secret_key_base: cc8cfa5b0f7de69c76468645c927746ac3d218129daa841aa2c0717ae2f9f9367932ecf212f8fc741501a32447036168ebf86986cbcfbab7dcf5545e0aa0facf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
